import React from "react";

const Terms = () => {
  return (
    <div>
      <section
        className="grid grid-cols-2 gap-4 text-white"
        data-aos-duration="600"
        data-aos="fade-in"
      >
        <div className="col1">
          <h1 className="text-center text-4xl">TERMS & CONDITIONS</h1>
          <p className="text-justify">
            COMMUNITY (CHAT AND CHILL) RULES AND GUIDELINE 1. Make sure you
            provide accurate information about your age and identity; Pretending
            to be younger or older than you are can put you and other users at
            risk. We have strict policies regarding age and we do not tolerate
            false identity. Please report any users who you think are lying
            about their age and report any users who you think are under 18
            years old. This will help us keep everyone safe on slattlife.com. 2.
            Blackmail, Impersonation, Scamming, Sexual extortion (or
            sextortion), hacking, and any attempt to wrongfully access
            information or money from other users or Slattlife.com itself are
            prohibited. If you engage in illegal behaviors, we may permanently
            suspend you from accessing our community website and depending on
            the severity, escalate to Law Enforcement. 3. We do not allow users
            to advertise, offer, and promote goods and services in exchange for
            money or other goods, or exchange of money from one another;
            especially when it comes to illegal or regulated products and
            services. for advert and promotion; please locate the contact
            section for more information about the advert. 4. Do not share
            financial information or payment details with another user you are
            chatting with via the platform, Slattlife.com is not a financial
            institution for financial transactions and we have very strict
            policies against scamming. Please report any users who are asking
            for money or financial information 5. We take action if users or
            members of our community encourage others to engage in harmful
            behaviors during Lives chat and chill or elsewhere on the platform
            and if harmful content is shared. 6. Be aware that the content you
            share on slattlife.com may be viewed by other users you interact
            with, as they may save your content through their devices (e.g. by
            taking a screenshot or recording on their phone) Although you have
            the freedom of expression to share images of yourself and also your
            instinct, beliefs, opinions, preferences, and information about your
            daily life if needed. Think carefully about what you want to share
            and keep in mind that another user has the ability to take a
            screenshot or record your content. 7. Enforcement Approach: As a
            user/member of the slattlife.com community website, you must agree
            to adhere to our Community Rules and Guidelines. If we receive a
            report of a violation of these rules and guidelines (either from
            another user or generated by our algorithms), we investigate and
            take appropriate action based on our guidelines. Our response will
            depend on how severe the violation is and the level of risk it poses
            for other community members. User reports are reviewed by safety
            specialists. We use automated tools to execute certain moderation
            actions (e.g. to take immediate action before any harm is done).
            More serious actions, such as suspending users, are decided by
            safety specialists and our Algorithm. We take the following
            enforcement approach: - In more severe cases and where someone is
            repeatedly violating our Community Guidelines, we may permanently
            suspend the user from the community website. - In instances
            involving a reporting obligation, potentially illegal behavior on
            our platform, or an emergency situation, we may work with law
            enforcement and other relevant entities to take additional action. -
            Our Algorithm Report provides details of the actions we took when
            our Community Guidelines were violated.
          </p>
        </div>
        <div className="col2">
          <h1 className="text-center text-4xl">PRIVACY POLICY</h1>
          <p>
            SAFETY AND PRIVACY (HUMAN RIGHT) on Slattlife.com, we seek to
            provide a community website for young talented, and determined
            people to express themselves freely, while still protecting their
            safety and privacy. We are committed to protecting human rights and
            following the principles set up in the United Nations Guiding
            Principles on Human Rights and Small Scale Businesses Our commitment
            to human rights is a key consideration during the development and
            drafting of our Community Guidelines, as well as in their day-to-day
            life application, whether in the context of content moderation or
            proactive detection. These guidelines and processes are informed by
            research, as well as the expertise of our Safety board; this ensures
            that specific attention is paid to the impact of these guidelines on
            more vulnerable or marginalised members of our community. Our
            consideration of Human Rights and our values is further reflected in
            additional ways: Our commitment to Safety and Privacy extends to our
            internal ways of working, through our Privacy Policy, Whistleblowing
            Policy, and Human Right Policy, Small- Scale Business Policy. Our
            Reports provide visibility on how our community guidelines are
            applied in practice, as well as data on our collaboration with Law
            Enforcement in the context of data requests or proactive reporting.
            By accessing or using these Services, you accept and agree to comply
            with these Rules and guidelines.
          </p>
        </div>
      </section>
    </div>
  );
};

export default Terms;
